######################################################################
# Automatically generated by qmake (1.04a) Fri Feb 21 19:06:45 2003
######################################################################

TEMPLATE = app
QT = core network xml
INCLUDEPATH += . ../../src
LIBS += ../../src/libqutexr.a
# Input
HEADERS += validationserver.h
SOURCES += test.cpp validationserver.cpp
