
FIND_PATH(MAGIC_INCLUDE_DIR magic.h
/usr/local/include
/usr/include
)

FIND_LIBRARY(MAGIC_LIBRARY
  NAMES magic
  PATHS /usr/lib /usr/local/lib
  )

IF (MAGIC_LIBRARY AND MAGIC_INCLUDE_DIR)
    SET(MAGIC_LIBRARIES ${MAGIC_LIBRARY})
    SET(MAGIC_INCLUDE_DIRS ${MAGIC_INCLUDE_DIR} ${MAGIC_INCLUDE_DIR}/poppler)
    SET(MAGIC_FOUND TRUE)
ELSE (MAGIC_LIBRARY AND MAGIC_INCLUDE_DIR)
  SET(MAGIC_FOUND FALSE)
ENDIF (MAGIC_LIBRARY AND MAGIC_INCLUDE_DIR)

